<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:property name="lidar_radius" value="0.075" />
    <xacro:property name="lidar_length" value="0.05" />
    <xacro:property name="lidar_mass" value="0.2" />


    <xacro:property name="lidar_x" value="${length/2 - lidar_radius}" />
    <xacro:property name="lidar_z" value="${height + lidar_length/2}" />

    <!-- lidar joint -->

    <joint name="lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar_link" />
        <origin xyz="${lidar_x} 0 ${lidar_z}" rpy="0.0 0.0 0" />

    </joint>


    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="red" />
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>


        <xacro:cylinder_inertia mass="${lidar_mass}" radius="${lidar_radius}"
            length="${lidar_length}">
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0" />
        </xacro:cylinder_inertia>

    </link>

    <gazebo reference="lidar_link">
        <sensor name='gpu_lidar' type='gpu_lidar'>
            <always_on>true</always_on>
            <visualize>true</visualize>
            <pose> 0 0 0 0 0 0 </pose>
            <update_rate>5</update_rate>
            <topic>scan</topic>
            <gz_frame_id>lidar_link</gz_frame_id>

            <lidar>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                    <resolution>0.01</resolution>
                </range>
            </lidar>
        </sensor>
    </gazebo>


</robot>